"""Ajout clinically_validated par analyse

Revision ID: 91f79dc01bc0
Revises: ce256e6de419
Create Date: 2026-08-14 13:05:04.600604

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '91f79dc01bc0'
down_revision: str | None = 'ce256e6de419'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('clinically_validated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'clinically_validated')
    # ### end Alembic commands ###
