"""Ajout signature et date de generation du rapport

Revision ID: ce256e6de419
Revises: ccfc5233db56
Create Date: 2026-08-08 00:24:52.973305

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ce256e6de419'
down_revision: str | None = 'ccfc5233db56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('report_signature', sa.String(length=64), nullable=True))
    op.add_column('analyses', sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'report_generated_at')
    op.drop_column('analyses', 'report_signature')
    # ### end Alembic commands ###
